### ISSUE TITLE
Client cannot move index file from /tmp dir in case if /tmp and cachedChartPath are on different partions

### ISSUE THREAD

**Issue by fidget83** [microbean/microbean-helm#156]
`/tmp` directory and `cachedChartPath` are located on different partitions on Centos 7.
Method `downloadIndexTo` is failed with error:

```
Caused by: org.microbean.helm.chart.resolver.ChartResolverException: /tmp/helm-index-3167391180822502416.yaml -> /usr/local/pem/kubernetes/.helm/repository/cache/helm-index.yaml:  Invalid cross-device link
	at org.microbean.helm.chart.repository.ChartRepository.resolve(ChartRepository.java:863)
	at test.App.main(App.java:31)
Caused by: java.nio.file.AtomicMoveNotSupportedException: /tmp/helm-index-3167391180822502416.yaml -> /usr/local/pem/kubernetes/.helm/repository/cache/helm-index.yaml: Неверная ссылка между устройствами
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:394)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.microbean.helm.chart.repository.ChartRepository.downloadIndexTo(ChartRepository.java:700)
	at org.microbean.helm.chart.repository.ChartRepository.getIndex(ChartRepository.java:573)
	at org.microbean.helm.chart.repository.ChartRepository.getCachedChartPath(ChartRepository.java:776)
	at org.microbean.helm.chart.repository.ChartRepository.resolve(ChartRepository.java:861)
	... 1 more
```

The method executed successfully, if not specify Copy Option `ATOMIC_MOVE`

**Comment by fidget83** [comment]
Hello, will it be possible to make a new version :)?

**Comment by ljnelson** [comment]
Fixed with 20491c8 and its parent.

**Comment by fidget83** [comment]
I've found another issue: without ATOMIC_MOVE we getting FileAlreadyExistsException when lib updates repository (with forceDownload option). I've created one more request.

Sorry for inconvenince :(

**Comment by ljnelson** [comment]
This is fixed.  I've deployed a [snapshot with the fix](https://oss.sonatype.org/content/repositories/snapshots/org/microbean/microbean-helm/2.8.2.1.0.8-SNAPSHOT/) until I can do a proper release.
