### ISSUE TITLE
Chart with any binary files fails during loading

### ISSUE THREAD

**Issue by mnnit-prashant** [microbean/microbean-helm#179]
We have charts which are successfully installed using helm client, but when we tried it with microbean helm it is failing during chart load.
Our chart contains some binary files.
chart loading is failing at
`StreamOrientedChartLoader.installAny(Builder chartBuilder, InputStream stream, String name)`
during `assert fileContents.isValidUtf8();`
Exception:-
```
java.lang.AssertionError
	at org.microbean.helm.chart.StreamOrientedChartLoader.installAny(StreamOrientedChartLoader.java:718)
	at org.microbean.helm.chart.StreamOrientedChartLoader.addFile(StreamOrientedChartLoader.java:376)
	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:264)
	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:213)
	at org.microbean.helm.chart.AbstractChartLoader.load(AbstractChartLoader.java:87)
```

**Comment by ljnelson** [comment]
Nice catch; I’ll fix this shortly and cut a new release. A workaround might be to disable assertions.

May I ask what binary files are in your chart?

**Comment by mnnit-prashant** [comment]
thanks Liard.
I can see that this fix is part of snapshot.
Are you going to put this in release version.
