### ISSUE TITLE
"Network is unreachable" error on OS X while using ReleaseManager.install

### ISSUE THREAD

**Issue by anurag-prakash-singh** [microbean/microbean-helm#183]
We are using microBean in a project to perform Helm chart installation. The setup details are as follows:

- client (which uses the microBean library) runs on a MacOS machine
- the client communicates with Tiller instance running in a Kubernetes cluster. For testing, we use minikube as the cluster

Here's how we create the `Tiller` and `ReleaseManager` objects (our project uses Scala but it's a JVM language too so the library can be imported and used just fine):

```
val tiller = new Tiller(kube) // kube is an instance of DefaultKubernetesClient
val relMgr = new ReleaseManager(tiller)
```
The problem is that when we call `relMgr.install`, we get the following exceptions:
```
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
    at abc.HelmActor.$anonfun$install$1(HelmActor.scala:96)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
    at scala.util.Success.$anonfun$map$1(Try.scala:251)
    at scala.util.Success.map(Try.scala:209)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.Status.asRuntimeException(Status.java:526)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
    at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
    at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: 0.0.0.0/0.0.0.0:62185
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
    ... 1 common frames omitted
Caused by: java.net.SocketException: Network is unreachable
    ... 11 common frames omitted

```
Interestingly, we also do some testing inside containers (so the client runs inside a container) and in the containerized environment, this exception doesn't occur.

We tried an experiment where we tried to open a `Socket` to talk to the forwarded port:
```
val socket = new Socket("0.0.0.0", localPortForward.getLocalPort)
```
This fails on MacOS as well, suggesting that there may be a routing issue here that causes the problem.

To get around this problem, we did this:
```
val tiller = {
    val localPortForward = Pods.forwardPort(kube.getHttpClient, kube.pods().inNamespace("default").withLabels(Tiller.DEFAULT_LABELS), Tiller.DEFAULT_PORT)
    val managedChannel = ManagedChannelBuilder
      .forAddress("127.0.0.1", localPortForward.getLocalPort())
      .idleTimeout(5L, TimeUnit.SECONDS)
      .keepAliveTime(30L, TimeUnit.SECONDS)
      .maxInboundMessageSize(Tiller.MAX_MESSAGE_SIZE)
      .usePlaintext(true)
      .build()

    new Tiller(managedChannel)
  }
```
This works. Naturally, we would like to avoid having to do this but aren't quite sure if there's another way to solve this problem (e.g. a configuration or property tweak).

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm.

As you have noted above, the networking issues are out of my hands.  I do give you the ability to pass in your own `ManagedChannel`, which is about the best I can do.

In terms of configuration, the [kubernetes-client project has some pretty good documentation on the subject](https://github.com/fabric8io/kubernetes-client/#configuring-the-client).  Perhaps what you're seeing is that a `DefaultKubernetesClient`, as you've created it with no arguments, can find no configuration in either environment variables, system properties or `~/.kube/config`?  It _will_ find configuration from within a pod, as the service account token will be automatically mounted and discovered.

**Comment by anurag-prakash-singh** [comment]
Thanks. We'll just stick with passing in our own `ManagedChannel` for now.
