### ISSUE TITLE
Install new Chart release - waiting forever/halt

### ISSUE THREAD

**Issue by eladh** [microbean/microbean-helm#193]
Hi,

I was following the instruction how to deploy new chart by using the release manager install.

its seems like the operation is succeeded but its seem that the gRpc call is stuck .

here is the relevant thread dump and code snippet 

```
 public static void main(String[] args) throws IOException {


        final URI uri = URI.create("https://kubernetes-charts.storage.googleapis.com/wordpress-0.6.6.tgz");
        final URL url = uri.toURL();
        Chart.Builder chart;
        try (final URLChartLoader chartLoader = new URLChartLoader()) {
            chart = chartLoader.load(url);
        }
        final DefaultKubernetesClient client = new DefaultKubernetesClient();

        client.namespaces();
        final Tiller tiller = new Tiller(client);
        final ReleaseManager releaseManager = new ReleaseManager(tiller);

        final InstallReleaseRequest.Builder requestBuilder = InstallReleaseRequest.newBuilder();

        requestBuilder.setTimeout(10);
        requestBuilder.setName("test-charts-wordpress"); // Set the Helm release name
        requestBuilder.setWait(false); // Wait for Pods to be ready
        requestBuilder.setNamespace("default");
        
        // Install the loaded chart with no user-supplied overrides.
        releaseManager.install(requestBuilder, chart);

    }
```

```
"OkHttp https://35.188.4.133/...@3931" prio=5 tid=0x17 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:171)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	  at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	  - locked <0x1036> (a java.lang.Object)
	  at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	  at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	  - locked <0x1037> (a sun.security.ssl.AppInputStream)
	  at okio.Okio$2.read(Okio.java:139)
	  at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	  at okio.RealBufferedSource.request(RealBufferedSource.java:67)
	  at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	  at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	  at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	  at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	  at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	  at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)

```

**Comment by ljnelson** [comment]
Hello; thanks for using microBean Helm, and my apologies for taking so long to get back to you!  Not sure how I missed this issue being filed!

I'm not sure what to tell you here: once the connection has been made, a combination of fabric8's Kubernetes client library and the Okio HTTP client take over.  Maybe you have a proxy issue and need to build the `ManagedChannel` differently when you create your `Tiller` instance?

**Comment by ljnelson** [comment]
Closing as this is not an issue related to microBean Helm.
