### ISSUE TITLE
NullPointerException, possibly triggered by embedded subchart?

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-helm#63]
Stack:

    Caused by: java.lang.NullPointerException
    	at org.microbean.helm.chart.StreamOrientedChartLoader.addFile(StreamOrientedChartLoader.java:271)
    	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:234)
    	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:187)
        	at org.microbean.helm.chart.AbstractChartLoader.load(AbstractChartLoader.java:87)

`fileName` is `null`, despite the `assert` (which probably wasn't on) saying it should never be.

**Comment by ljnelson** [comment]
Root issue is that this path:

    chart-with-subcharts/charts/minio-0.3.0.tgz

…is not matched by this regular expression:

    ^.+/charts/[^._][^/]+/(.+)$

**Comment by ljnelson** [comment]
There's also a problem with the `basename` method.  Given a string like `minio-0.3.0.tgz`, I would expect it to return `minio-0.3.0.tgz` but it returns the empty string.

**Comment by ljnelson** [comment]
Fixed with cf5d1dd
