### ISSUE TITLE
AssertionError in StreamOrientedChartLoader

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-helm#74]
`io/fabric8/platform/packages/ingress/4.0.208/ingress-4.0.208-helm.tar.gz`

Arbitrarily chose `io.fabric8.platform.packages:ingress:4.0.208` with a packaging type of `tar.gz` and a classifier of `helm`.  This particular chart, when loaded by the usual microbean-helm mechanisms, yields an `AssertionError` like so:

    java.lang.AssertionError
    	at org.microbean.helm.chart.StreamOrientedChartLoader.addFile(StreamOrientedChartLoader.java:273)
    	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:238)
    	at org.microbean.helm.chart.StreamOrientedChartLoader.load(StreamOrientedChartLoader.java:191)

**Comment by ljnelson** [comment]
Investigating; a straight load of this chart leads to no errors.  The stack trace is essentially the same as that surfaced by #63.  It is triggered by the [microbean-helm-maven](https://github.com/microbean/microbean-helm-maven) project, which in this case uses a simple `AbstractChartLoader` no different from that used in `TestIssue63`.  Something very fishy here; the problem is not yet understood.

**Comment by ljnelson** [comment]
Aha! I have a reproducer.  The issue is directory entries in the stream.  This issue differs from #63 in that the reproducer doesn't use a `DirectoryChartLoader`.  Likely there is some unaccounted-for case of directory entries being present in this particular chart where in others they aren't.
